libraries/botbuilder/tests/botFrameworkAdapter.test.js

Fixes 799
The description of the test was modified to match the method it was testing. 
- Change 'signOutUser()' to 'getAadTokens()' in the test description 
No testing required

[MANX-464] Change test description to match implementation

---

package.json

Fixes 744
Even though it is necessary to have lerna installed globally to run commands such as `npm i` and `npm run build`, it is not listed on the devDependencies. This causes issues when trying to intall.
To avoid this, we added lerna as a devDependency on the `package.json` file.
- Add the `"lerna": "^3.2.1"` line to the `package.json`
Before adding the line:
After adding the line:

[MANX-417] Add lerna to package.json devDependencies

---

libraries/testbot/bots/echoBot.js
libraries/testbot/bots/myBot.js
libraries/testbot/index.js
libraries/testbot/package-lock.json

We updated the testbot project to have parity with the Botbuilder-DotNet implementation in the [PR#1946](https://github.com/microsoft/botbuilder-dotnet/pull/1946) that configured an endpoint for each bot in the testbot project. To do that, we separated the bot logic from index.js file and added a new post method with the route '/api/testbot' to handle the messages sent to the testbot.
Additionally, we updated the package-lock.json to get the latest version of the botbuilder libraries.
- Separate the bot logic from the index.js file
- Update the package-lock.json

Update testbot to parity with DotNet

---

libraries/botbuilder-ai/src/luis-client/luisClient.ts

Refactor (extract method) of LuisClient.ts for simplification, increased reusability and readability.
Originally the plan was to use `path.join()` and _template literals_. However, this approach did not worked.
- `path.join()` had issues eliminating one slash in the `https://` prefix.
- As a corollary of this issue, the template literals were not necessary.
Now in the methods: 
- `predictionResolvePost`
- `predictionResolveGet` 
There is an invocation of the new private function `getLocalURL`, passing the appId as the only parameter.
signature:
`private getLocalURL(appId: string): string`
This function is very small, and takes care of using the encodeURIComponent() function internally, returning the local URL ready to use. It has several simplifications from the original code.
The local …

[BotBuilder-AI] Update / Refactor luisClient.ts

---

libraries/botbuilder-ai/package.json
libraries/botbuilder-ai/src/luis-client/luisClient.ts

Refactor with substitution from magic numbers to enumerated constants.
- Added [http-status-codes](https://www.npmjs.com/package/http-status-codes)
- Replaced magic numbers '200' and '300' with enumerated constants.
Test passed successfully.

[BotBuilder-AI] Replaced numbers '200' and '300' to verify the response status code with enumerated constants

---

libraries/botbuilder-ai/src/luis-client/luisClient.ts

The class `LuisClient` had a `protected` field (_basePath). We changed it to `private` and added documentation to the constructor. We received feedback from [stevengum](https://github.com/stevengum). More details [here](https://github.com/microsoft/botbuilder-js/pull/1107#discussion_r314857347).
Changes:
*luisClient.ts*
- Changed accesibility modifier for `_basePath` from `protected` to `private`.
- Added documentation for constructor of `LuisClient` class.
The next image shows the result of the local tests.

Changed _basePath from protected to private

---

libraries/botbuilder-ai/src/luis-client/luisClient.ts

Removed `_useQueryString` member from `LuisClient` as the _LuisClient_ class nor any other classes reference it.

[BotBuilder-AI] Removed useQueryString

---

package.json

Using ESLint now lets TSLint deprecated, and can be easily removed.
**package.json**: removed references:
-  `tslint` 
- `tslint-microsoft-contrib`
All the tests run successfully.

Removed references to TSLint

---

package.json

Modified the script in the Package JSON in order to stop using Chrome as the default Browser.
We will work with three or more different Browsers, so in order to not have conflicts in the future, we had to remove the Browser Chrome as the default test Browser and instead, we will test each environment in the Pipeline.
- Remove "chrome" from the Script
In the image we tested Edge and Chrome (only Chrome succeeded, because we didn't have installed yet the Web Driver for Edge)

[BotBuilder-JS] Add scripts to package JSON to run the functional tests for each environments

---

libraries/adaptive-expressions/src/builtinFunctions/divide.ts
libraries/adaptive-expressions/src/builtinFunctions/element.ts
libraries/adaptive-expressions/src/builtinFunctions/empty.ts
libraries/adaptive-expressions/src/builtinFunctions/endsWith.ts
libraries/adaptive-expressions/src/builtinFunctions/equal.ts
libraries/adaptive-expressions/src/builtinFunctions/exists.ts
libraries/adaptive-expressions/src/builtinFunctions/first.ts
libraries/adaptive-expressions/src/builtinFunctions/flatten.ts
libraries/adaptive-expressions/src/builtinFunctions/float.ts
libraries/adaptive-expressions/src/builtinFunctions/floor.ts
libraries/adaptive-expressions/src/builtinFunctions/foreach.ts

[internal] Apply xref links for adaptive-expressions/builtFunctions-3

---

libraries/botframework-streaming/src/assemblers/payloadAssembler.ts
libraries/botframework-streaming/src/contentStream.ts
libraries/botframework-streaming/src/disassemblers/cancelDisassembler.ts
libraries/botframework-streaming/src/disassemblers/httpContentStreamDisassembler.ts
libraries/botframework-streaming/src/disassemblers/payloadDisassembler.ts
libraries/botframework-streaming/src/disassemblers/requestDisassembler.ts
libraries/botframework-streaming/src/disassemblers/responseDisassembler.ts
libraries/botframework-streaming/src/httpContentStream.ts
libraries/botframework-streaming/src/subscribableStream.ts

[internal] Apply xref links for southworks/add/jsdoc/botframework streaming

---

libraries/botframework-config/src/botRecipe.ts

[internal] Apply xref links for southworks/add/jsdoc/botframework-config

---

libraries/adaptive-expressions/src/builtinFunctions/accessor.ts
libraries/adaptive-expressions/src/builtinFunctions/add.ts
libraries/adaptive-expressions/src/builtinFunctions/addDays.ts
libraries/adaptive-expressions/src/builtinFunctions/addHours.ts
libraries/adaptive-expressions/src/builtinFunctions/addMinutes.ts
libraries/adaptive-expressions/src/builtinFunctions/addOrdinal.ts
libraries/adaptive-expressions/src/builtinFunctions/addProperty.ts
libraries/adaptive-expressions/src/builtinFunctions/addSeconds.ts
libraries/adaptive-expressions/src/builtinFunctions/addToTime.ts
libraries/adaptive-expressions/src/builtinFunctions/and.ts
libraries/adaptive-expressions/src/builtinFunctions/average.ts
libraries/adaptive-expressions/src/builtinFunctions/base64.ts
libraries/adaptive-expressions/src/builtinFunctions/base64ToBinary.ts
libraries/adaptive-expressions/src/builtinFunctions/base64ToString.ts
libraries/adaptive-expressions/src/builtinFunctions/binary.ts
libraries/adaptive-expressions/src/builtinFunctions/bool.ts

PR 2843 in MS, #165 in SW
Regarding the requested changes: I believe the comment is out of scope, referencing _coding style_ on a linter spacing fix.

[internal] Apply xref links for southworks/add/jsdoc/adaptive-expressions/builtFunctions-1

---

libraries/botbuilder-lg/src/position.ts
libraries/botbuilder-lg/src/range.ts
libraries/botbuilder-lg/src/sourceRange.ts
libraries/botbuilder-lg/src/staticChecker.ts
libraries/botbuilder-lg/src/template.ts
libraries/botbuilder-lg/src/templateException.ts
libraries/botbuilder-lg/src/templateImport.ts
libraries/botbuilder-lg/src/templates.ts
libraries/botbuilder-lg/src/templatesParser.ts

PR 2830 in MS, #155 in SW
Feedback applied to use xref to link to other methods and missing documentation instances.
Changes requested for `Template` don't apply to our additions.
There's also one question regarding our C# port convention for private methods. The method `expressionParser` is documented for C#, so we ported it.

[internal] Apply xref links for southworks/add/jsdoc/botbuilder-lg

---

libraries/botbuilder-dialogs-declarative/src/builderRegistration.ts
libraries/botbuilder-dialogs-declarative/src/converterRegistration.ts
libraries/botbuilder-dialogs-declarative/src/factory/customTypeBuilder.ts
libraries/botbuilder-dialogs-declarative/src/factory/defaultTypeBuilder.ts
libraries/botbuilder-dialogs-declarative/src/resources/resourceExplorer.ts
libraries/botbuilder-dialogs-declarative/src/resources/resourceProvider.ts

[internal] Apply xref links for southworks/add/jsdoc/botbuilder-dialogs-declarative

---

libraries/botbuilder-lg/src/analyzer.ts
libraries/botbuilder-lg/src/analyzerResult.ts
libraries/botbuilder-lg/src/customizedMemory.ts
libraries/botbuilder-lg/src/diagnostic.ts
libraries/botbuilder-lg/src/errorListener.ts
libraries/botbuilder-lg/src/evaluationOptions.ts
libraries/botbuilder-lg/src/evaluationTarget.ts
libraries/botbuilder-lg/src/evaluator.ts
libraries/botbuilder-lg/src/expander.ts
libraries/botbuilder-lg/src/extractor.ts
libraries/botbuilder-lg/src/lgResource.ts

Applied feedback from PR 2828 in MS.
- Added missing returns
- Minor fixes in comments
- Added xref links where possible
Missing to bring changes from main and solve conflicts.

[internal] Apply xref links and feedback for jsdoc/botbuilder-lg-root files

---

libraries/botframework-connector/src/auth/appCredentials.ts
libraries/botframework-connector/src/auth/authenticationError.ts
libraries/botframework-connector/src/auth/certificateAppCredentials.ts
libraries/botframework-connector/src/auth/claimsIdentity.ts
libraries/botframework-connector/src/auth/credentialProvider.ts
libraries/botframework-connector/src/auth/jwtTokenExtractor.ts
libraries/botframework-connector/src/auth/microsoftAppCredentials.ts
libraries/botframework-connector/src/auth/openIdMetadata.ts
libraries/botframework-connector/src/emulatorApiClient.ts
libraries/botframework-connector/src/teams/operations/teams.ts

PR 2827 in MS, #152 in SW
Feedback applied to use xref to link to other methods and add a missing `return` tag to `openIdMetadata`.

[internal] Apply xref links for botframework-connector

---

libraries/botbuilder-dialogs-adaptive/src/actionContext.ts
libraries/botbuilder-dialogs-adaptive/src/adaptiveDialog.ts
libraries/botbuilder-dialogs-adaptive/src/adaptiveDialogComponentRegistration.ts
libraries/botbuilder-dialogs-adaptive/src/adaptiveTypeBuilder.ts
libraries/botbuilder-dialogs-adaptive/src/customDialogTypeBuilder.ts
libraries/botbuilder-dialogs-adaptive/src/languagePolicy.ts

[internal] Apply xref links for southworks/add/jsdoc/botbuilder-dialogs-adaptive/root

---

libraries/botbuilder-applicationinsights/src/applicationInsightsTelemetryClient.ts

Applied feedback from PR 2838 in MS, 159 in SW

[internal] Apply xref links for southworks/add/jsdoc/botbuilder-applicationinsights files

---

libraries/adaptive-expressions/src/builtinFunctions/formatDateTime.ts
libraries/adaptive-expressions/src/builtinFunctions/formatEpoch.ts
libraries/adaptive-expressions/src/builtinFunctions/formatNumber.ts
libraries/adaptive-expressions/src/builtinFunctions/formatTicks.ts
libraries/adaptive-expressions/src/builtinFunctions/getFutureTime.ts
libraries/adaptive-expressions/src/builtinFunctions/getNextViableDate.ts
libraries/adaptive-expressions/src/builtinFunctions/getNextViableTime.ts
libraries/adaptive-expressions/src/builtinFunctions/getPastTime.ts
libraries/adaptive-expressions/src/builtinFunctions/getPreviousViableDate.ts
libraries/adaptive-expressions/src/builtinFunctions/getPreviousViableTime.ts
libraries/adaptive-expressions/src/builtinFunctions/getProperty.ts
libraries/adaptive-expressions/src/builtinFunctions/getTimeOfDay.ts
libraries/adaptive-expressions/src/builtinFunctions/greaterThan.ts
libraries/adaptive-expressions/src/builtinFunctions/greaterThanOrEqual.ts
libraries/adaptive-expressions/src/builtinFunctions/if.ts
libraries/adaptive-expressions/src/builtinFunctions/ignore.ts

[internal] Apply xref links for southworks/add/jsdoc/adaptive-expressions/builtFunctions-4

---

libraries/botbuilder-core/src/activityFactory.ts
libraries/botbuilder-core/src/activityHandler.ts
libraries/botbuilder-core/src/autoSaveStateMiddleware.ts
libraries/botbuilder-core/src/botStatePropertyAccessor.ts
libraries/botbuilder-core/src/botTelemetryClient.ts
libraries/botbuilder-core/src/browserStorage.ts
libraries/botbuilder-core/src/cardFactory.ts
libraries/botbuilder-core/src/memoryStorage.ts
libraries/botbuilder-core/src/middlewareSet.ts
libraries/botbuilder-core/src/skypeMentionNormalizeMiddleware.ts
libraries/botbuilder-core/src/testAdapter.ts
libraries/botbuilder-core/src/turnContextStateCollection.ts

[internal] Apply xref links for southworks/add/jsdoc/botbuilder-core

---

libraries/adaptive-expressions/src/builtinFunctions/indexOf.ts
libraries/adaptive-expressions/src/builtinFunctions/indicesAndValues.ts
libraries/adaptive-expressions/src/builtinFunctions/int.ts
libraries/adaptive-expressions/src/builtinFunctions/intersection.ts
libraries/adaptive-expressions/src/builtinFunctions/isArray.ts
libraries/adaptive-expressions/src/builtinFunctions/isBoolean.ts
libraries/adaptive-expressions/src/builtinFunctions/isDate.ts
libraries/adaptive-expressions/src/builtinFunctions/isDateRange.ts
libraries/adaptive-expressions/src/builtinFunctions/isDateTime.ts
libraries/adaptive-expressions/src/builtinFunctions/isDefinite.ts
libraries/adaptive-expressions/src/builtinFunctions/isDuration.ts
libraries/adaptive-expressions/src/builtinFunctions/isFloat.ts
libraries/adaptive-expressions/src/builtinFunctions/isInteger.ts
libraries/adaptive-expressions/src/builtinFunctions/isMatch.ts
libraries/adaptive-expressions/src/builtinFunctions/isObject.ts
libraries/adaptive-expressions/src/builtinFunctions/isPresent.ts
libraries/adaptive-expressions/src/builtinFunctions/isString.ts
libraries/adaptive-expressions/src/builtinFunctions/isTime.ts
libraries/adaptive-expressions/src/builtinFunctions/isTimeRange.ts

[internal] Apply xref links for southworks/add/jsdoc/adaptive-expressions/builtFunctions-5

---

libraries/adaptive-expressions/src/builtinFunctions/jPath.ts
libraries/adaptive-expressions/src/builtinFunctions/json.ts
libraries/adaptive-expressions/src/builtinFunctions/jsonStringify.ts
libraries/adaptive-expressions/src/builtinFunctions/last.ts
libraries/adaptive-expressions/src/builtinFunctions/lastIndexOf.ts
libraries/adaptive-expressions/src/builtinFunctions/length.ts
libraries/adaptive-expressions/src/builtinFunctions/lessThan.ts
libraries/adaptive-expressions/src/builtinFunctions/lessThanOrEqual.ts
libraries/adaptive-expressions/src/builtinFunctions/max.ts
libraries/adaptive-expressions/src/builtinFunctions/merge.ts
libraries/adaptive-expressions/src/builtinFunctions/min.ts
libraries/adaptive-expressions/src/builtinFunctions/mod.ts
libraries/adaptive-expressions/src/builtinFunctions/month.ts
libraries/adaptive-expressions/src/builtinFunctions/multiply.ts

[internal] Apply xref links for southworks/add/jsdoc/adaptive-expressions/builtFunctions-6

---

libraries/adaptive-expressions/src/builtinFunctions/multivariateNumericEvaluator.ts
libraries/adaptive-expressions/src/builtinFunctions/newGuid.ts
libraries/adaptive-expressions/src/builtinFunctions/not.ts
libraries/adaptive-expressions/src/builtinFunctions/notEqual.ts
libraries/adaptive-expressions/src/builtinFunctions/numberTransformEvaluator.ts
libraries/adaptive-expressions/src/builtinFunctions/numericEvaluator.ts
libraries/adaptive-expressions/src/builtinFunctions/optional.ts
libraries/adaptive-expressions/src/builtinFunctions/or.ts
libraries/adaptive-expressions/src/builtinFunctions/power.ts
libraries/adaptive-expressions/src/builtinFunctions/rand.ts
libraries/adaptive-expressions/src/builtinFunctions/range.ts
libraries/adaptive-expressions/src/builtinFunctions/removeProperty.ts
libraries/adaptive-expressions/src/builtinFunctions/replace.ts
libraries/adaptive-expressions/src/builtinFunctions/replaceIgnoreCase.ts
libraries/adaptive-expressions/src/builtinFunctions/round.ts

[internal] Apply xref links for southworks/add/jsdoc/adaptive-expressions/builtFunctions-7

---

libraries/adaptive-expressions/src/builtinFunctions/select.ts
libraries/adaptive-expressions/src/builtinFunctions/sentenceCase.ts
libraries/adaptive-expressions/src/builtinFunctions/setPathToValue.ts
libraries/adaptive-expressions/src/builtinFunctions/setProperty.ts
libraries/adaptive-expressions/src/builtinFunctions/skip.ts
libraries/adaptive-expressions/src/builtinFunctions/sortBy.ts
libraries/adaptive-expressions/src/builtinFunctions/sortByDescending.ts
libraries/adaptive-expressions/src/builtinFunctions/split.ts
libraries/adaptive-expressions/src/builtinFunctions/startOfDay.ts
libraries/adaptive-expressions/src/builtinFunctions/startOfHour.ts
libraries/adaptive-expressions/src/builtinFunctions/startOfMonth.ts
libraries/adaptive-expressions/src/builtinFunctions/startsWith.ts
libraries/adaptive-expressions/src/builtinFunctions/string.ts
libraries/adaptive-expressions/src/builtinFunctions/stringTransformEvaluator.ts
libraries/adaptive-expressions/src/builtinFunctions/subArray.ts

[internal] Apply xref links for southworks/add/jsdoc/adaptive-expressions/builtFunctions-8

---

libraries/adaptive-expressions/src/builtinFunctions/substring.ts
libraries/adaptive-expressions/src/builtinFunctions/subtract.ts
libraries/adaptive-expressions/src/builtinFunctions/subtractFromTime.ts
libraries/adaptive-expressions/src/builtinFunctions/sum.ts
libraries/adaptive-expressions/src/builtinFunctions/take.ts
libraries/adaptive-expressions/src/builtinFunctions/ticks.ts
libraries/adaptive-expressions/src/builtinFunctions/ticksToDays.ts
libraries/adaptive-expressions/src/builtinFunctions/ticksToHours.ts
libraries/adaptive-expressions/src/builtinFunctions/ticksToMinutes.ts
libraries/adaptive-expressions/src/builtinFunctions/timeTransformEvaluator.ts
libraries/adaptive-expressions/src/builtinFunctions/titleCase.ts
libraries/adaptive-expressions/src/builtinFunctions/toLower.ts
libraries/adaptive-expressions/src/builtinFunctions/toUpper.ts
libraries/adaptive-expressions/src/builtinFunctions/trim.ts
libraries/adaptive-expressions/src/builtinFunctions/union.ts

[internal] Apply xref links for southworks/add/jsdoc/adaptive-expressions/builtFunctions-9

---

libraries/adaptive-expressions/src/converters/arrayExpressionConverter.ts
libraries/adaptive-expressions/src/converters/boolExpressionConverter.ts
libraries/adaptive-expressions/src/converters/enumExpressionConverter.ts
libraries/adaptive-expressions/src/converters/expressionConverter.ts
libraries/adaptive-expressions/src/converters/intExpressionConverter.ts
libraries/adaptive-expressions/src/converters/numberExpressionConverter.ts
libraries/adaptive-expressions/src/converters/objectExpressionConverter.ts
libraries/adaptive-expressions/src/converters/stringExpressionConveter.ts
libraries/adaptive-expressions/src/converters/valueExpressionConverter.ts

[internal] Apply xref links for adaptive-expressions/converters

---

libraries/adaptive-expressions/src/builtinFunctions/unique.ts
libraries/adaptive-expressions/src/builtinFunctions/uriComponent.ts
libraries/adaptive-expressions/src/builtinFunctions/uriComponentToString.ts
libraries/adaptive-expressions/src/builtinFunctions/uriHost.ts
libraries/adaptive-expressions/src/builtinFunctions/uriPath.ts
libraries/adaptive-expressions/src/builtinFunctions/uriPathAndQuery.ts
libraries/adaptive-expressions/src/builtinFunctions/uriPort.ts
libraries/adaptive-expressions/src/builtinFunctions/uriQuery.ts
libraries/adaptive-expressions/src/builtinFunctions/uriScheme.ts
libraries/adaptive-expressions/src/builtinFunctions/utcNow.ts
libraries/adaptive-expressions/src/builtinFunctions/where.ts
libraries/adaptive-expressions/src/builtinFunctions/year.ts

[internal] Apply xref links for southworks/add/jsdoc/adaptive-expressions/builtFunctions-10

---

libraries/teams-scenarios/actionBasedMessagingExtension-fetchTask/src/actionBasedMessagingExtensionFetchBot.ts
libraries/teams-scenarios/actionBasedMessagingExtension-fetchTask/src/adaptiveCardHelper.ts
libraries/teams-scenarios/actionBasedMessagingExtension-fetchTask/src/cardResponseHelpers.ts
libraries/teams-scenarios/actionBasedMessagingExtension/src/actionBasedMessagingExtensionBot.ts
libraries/teams-scenarios/activityUpdateAndDelete/src/activityUpdateAndDeleteBot.ts
libraries/teams-scenarios/adaptiveCards/src/adaptiveCardsBot.ts
libraries/teams-scenarios/cardBotFramework/src/cardsBot.ts
libraries/teams-scenarios/integrationBot/src/activityLog.ts
libraries/teams-scenarios/integrationBot/src/adaptiveCardHelper.ts
libraries/teams-scenarios/integrationBot/src/cardResponseHelpers.ts
libraries/teams-scenarios/integrationBot/src/integrationBot.ts
libraries/teams-scenarios/integrationBot/src/teamsTenantFilteringMiddleware.ts

[internal] Apply xref links for southworks/add/jsdoc/teams-scenarios-root

---

libraries/adaptive-expressions/src/expressionProperties/arrayExpression.ts
libraries/adaptive-expressions/src/expressionProperties/boolExpression.ts
libraries/adaptive-expressions/src/expressionProperties/enumExpression.ts
libraries/adaptive-expressions/src/expressionProperties/expressionProperty.ts
libraries/adaptive-expressions/src/expressionProperties/intExpression.ts
libraries/adaptive-expressions/src/expressionProperties/numberExpression.ts
libraries/adaptive-expressions/src/expressionProperties/objectExpression.ts
libraries/adaptive-expressions/src/expressionProperties/stringExpression.ts
libraries/adaptive-expressions/src/expressionProperties/valueExpression.ts

[internal] Apply xref links for southworks/add/jsdoc/adaptive-expressions/expressionProperties

---

libraries/adaptive-expressions/src/constant.ts
libraries/adaptive-expressions/src/expression.ts
libraries/adaptive-expressions/src/functionTable.ts
libraries/adaptive-expressions/src/memory/simpleObjectMemory.ts
libraries/adaptive-expressions/src/memory/stackedMemory.ts
libraries/adaptive-expressions/src/options.ts
libraries/adaptive-expressions/src/parser/expressionParser.ts
libraries/adaptive-expressions/src/parser/parseErrorListener.ts

[internal] Apply xref links for southworks/add/jsdoc/adaptive-expressions/root-memory-parser

---

libraries/teams-scenarios/conversationUpdate/src/conversationUpdateBot.ts
libraries/teams-scenarios/fileUpload/src/fileUploadBot.ts
libraries/teams-scenarios/link-unfurling/src/linkUnfurling.ts
libraries/teams-scenarios/mentionsBot/src/mentionsBot.ts
libraries/teams-scenarios/messageReaction/src/activityLog.ts
libraries/teams-scenarios/messageReaction/src/messageReactionBot.ts
libraries/teams-scenarios/messagingExtensionAuth/src/messagingExtensionAuthBot.ts
libraries/teams-scenarios/messagingExtensionConfig/src/messagingExtensionConfigBot.ts
libraries/teams-scenarios/notificationOnly/src/notificationOnlyBot.ts
libraries/teams-scenarios/office365Card/src/office365CardsBot.ts
libraries/teams-scenarios/replyToChannel/src/replyToChannelBot.ts
libraries/teams-scenarios/roster/src/rosterBot.ts
libraries/teams-scenarios/searchBasedMessagingExtension/src/teamsSearchExtensionBot.ts
libraries/teams-scenarios/taskModule/src/taskModuleBot.ts

[internal] Apply xref links for southworks/add/jsdoc/teams-scenarios-files

---

libraries/botbuilder-dialogs-adaptive/src/converters/activityTemplateConverter.ts
libraries/botbuilder-dialogs-adaptive/src/converters/dialogExpressionConverter.ts
libraries/botbuilder-dialogs-adaptive/src/converters/languageGeneratorConverter.ts
libraries/botbuilder-dialogs-adaptive/src/converters/multiLanguageRecognizerConverter.ts
libraries/botbuilder-dialogs-adaptive/src/converters/recognizerConverter.ts
libraries/botbuilder-dialogs-adaptive/src/converters/textTemplateConverter.ts
libraries/botbuilder-dialogs-adaptive/src/expressions/dialogExpression.ts
libraries/botbuilder-dialogs-adaptive/src/generators/languageGeneratorManager.ts
libraries/botbuilder-dialogs-adaptive/src/generators/resourceMultiLanguageGenerator.ts
libraries/botbuilder-dialogs-adaptive/src/generators/templateEngineLanguageGenerator.ts
libraries/botbuilder-dialogs-adaptive/src/luis/luisAdaptiveRecognizer.ts

PR 2857 in MS, #176 in SW
The conflicts with `main` are not solved in this PR to don't add irrelevant changes to review

[internal] Apply xref links for southworks/add/jsdoc/botbuilder-dialogs-adaptive/converters

---

libraries/botframework-streaming/src/payloads/payloadAssemblerManager.ts
libraries/botframework-streaming/src/payloads/requestManager.ts
libraries/botframework-streaming/src/payloads/sendOperations.ts
libraries/botframework-streaming/src/payloads/streamManager.ts
libraries/botframework-streaming/src/webSocket/browserWebSocket.ts
libraries/botframework-streaming/src/webSocket/factories/nodeWebSocketFactory.ts
libraries/botframework-streaming/src/webSocket/nodeWebSocket.ts

PR 2825 in MS, #151 in SW
This PR doesn't include the conflict resolution.

[internal] Apply xref links for botframework-streaming-websocket

---

libraries/botbuilder/src/fileTranscriptStore.ts
libraries/botbuilder/src/inspectionMiddleware.ts
libraries/botbuilder/src/statusCodeError.ts
libraries/botbuilder/src/teamsActivityHandler.ts
libraries/botbuilder/src/teamsActivityHelpers.ts
libraries/botbuilder/src/teamsInfo.ts

[internal] Apply xref links for southworks/add/jsdoc/botbuilder

---

libraries/botbuilder-dialogs/src/memory/dialogStateManager.ts

PR 2824 in MS, #149 in SW
This PR doesn't include the conflict resolution.

[internal] Apply xref links for southworks/add/jsdoc/botbuilder-dialogs/memory

---

libraries/botbuilder-dialogs/src/memory/pathResolvers/aliasPathResolver.ts
libraries/botbuilder-dialogs/src/memory/pathResolvers/atAtPathResolver.ts
libraries/botbuilder-dialogs/src/memory/pathResolvers/atPathResolver.ts
libraries/botbuilder-dialogs/src/memory/pathResolvers/dollarPathResolver.ts
libraries/botbuilder-dialogs/src/memory/pathResolvers/hashPathResolver.ts
libraries/botbuilder-dialogs/src/memory/pathResolvers/percentPathResolver.ts

PR 2823 in MS, #148 in SW
This PR doesn't include conflict resolution.

[internal] Apply xref links for southworks/add/jsdoc/botbuilder-dialogs/memory-path-resolver

---

libraries/botbuilder/src/activityValidator.ts
libraries/botbuilder/src/botFrameworkAdapter.ts
libraries/botbuilder/src/botFrameworkHttpClient.ts
libraries/botbuilder/src/channelServiceHandler.ts
libraries/botbuilder/src/skills/skillHttpClient.ts
libraries/botbuilder/src/streaming/streamingHttpClient.ts
libraries/botbuilder/src/streaming/tokenResolver.ts

[internal] Apply xref links for southworks/add/jsdoc/botbuilder-skills

---

libraries/botbuilder-dialogs/src/memory/scopes/botStateMemoryScope.ts
libraries/botbuilder-dialogs/src/memory/scopes/classMemoryScope.ts
libraries/botbuilder-dialogs/src/memory/scopes/conversationMemoryScope.ts
libraries/botbuilder-dialogs/src/memory/scopes/dialogClassMemoryScope.ts
libraries/botbuilder-dialogs/src/memory/scopes/dialogMemoryScope.ts
libraries/botbuilder-dialogs/src/memory/scopes/memoryScope.ts
libraries/botbuilder-dialogs/src/memory/scopes/settingsMemoryScope.ts
libraries/botbuilder-dialogs/src/memory/scopes/thisMemoryScope.ts
libraries/botbuilder-dialogs/src/memory/scopes/turnMemoryScope.ts
libraries/botbuilder-dialogs/src/memory/scopes/userMemoryScope.ts

PR 2822 in MS, #147 in SW
This PR doesn't include conflict resolution.

[internal] Apply xref links for southworks/add/jsdoc/botbuilder dialogs/memory scopes

---

libraries/botbuilder-azure/src/azureBlobTranscriptStore.ts

PR 2817 in MS, #141 in SW
This PR doesn't have conflicts.

[internal] Apply xref links for southworks/add/documentation/botbuilder-azure

---

libraries/botbuilder-dialogs/src/componentDialog.ts
libraries/botbuilder-dialogs/src/dialogContext.ts
libraries/botbuilder-dialogs/src/dialogHelper.ts
libraries/botbuilder-dialogs/src/dialogManager.ts
libraries/botbuilder-dialogs/src/skillDialog.ts
libraries/botbuilder-dialogs/src/waterfallDialog.ts

[internal] Apply xref links for southworks/add/jsdoc/botbuilder-dialogs/root

---

libraries/botbuilder-dialogs/src/choices/choiceFactory.ts
libraries/botbuilder-dialogs/src/prompts/activityPrompt.ts
libraries/botbuilder-dialogs/src/prompts/choicePrompt.ts
libraries/botbuilder-dialogs/src/prompts/confirmPrompt.ts
libraries/botbuilder-dialogs/src/prompts/datetimePrompt.ts
libraries/botbuilder-dialogs/src/prompts/numberPrompt.ts
libraries/botbuilder-dialogs/src/prompts/oauthPrompt.ts
libraries/botbuilder-dialogs/src/prompts/prompt.ts
libraries/botbuilder-dialogs/src/prompts/textPrompt.ts

[internal] Apply xref links for southworks/add/jsdoc/botbuilder-dialogs/choices-prompts

---

libraries/botbuilder-ai/src/luisRecognizer.ts
libraries/botbuilder-ai/src/luisRecognizerOptions.ts
libraries/botbuilder-ai/src/luisRecognizerOptionsV2.ts
libraries/botbuilder-ai/src/luisRecognizerOptionsV3.ts
libraries/botbuilder-ai/src/qnaMaker.ts

[internal] Apply xref links for southworks/add/documentation/botbuilder-ai

---

libraries/botbuilder-dialogs-adaptive/package.json
libraries/botbuilder-dialogs-adaptive/src/actions/getActivityMembers.ts
libraries/botbuilder-dialogs-adaptive/src/actions/getConversationMembers.ts

Fixes # 3922
#minor
This PR ports the changes in [BotBuider-DotNet](https://github.com/microsoft/botbuilder-dotnet/pull/ 5874)  to Corrected GetConversationMembers in Adaptive.Runtime to use TeamsInfo helper class rather than rely on BotFrameworkAdapter functions that aren't available now that CoreBotAdapter derives from CloudAdapter and not BotFrameworkAdapter.
- getActitivityMemebers.ts
- Remove BotFrameworkAdapter
- Create a private function, which gets the connector client and returns the accounts info
- getConversationsMemebers.ts
- Remove BotFrameworkAdapter
- Create a private function, which gets the connector client and returns the conversation's members info
These images show the unit tests passing after the changes.

port: [#3922] Corrected GetConversationMembers to use TeamsInfo helper class rather… (#5874)
